### ISSUE TITLE
CHECK_FAILED / Update information fails to be queried

### ISSUE THREAD

**Issue by MamdRoyalWorld** [darkang3lz92/huawei_in_app_update#7]
When i try to run the code 
        final upgradeInfo = await HuaweiInAppUpdate.checkForUpdate();

i will get this error 
CHECK_FAILED / Update information fails to be queried
Please Help

**Comment by humzashahid-mobile** [comment]
final upgradeInfo = await HuaweiInAppUpdate.checkForUpdate();
above object of upgradeInfo I got null . check below output is the object value : 

UpgradeInfo{updateAvailable: false, appId: null, appName: null, packageName: null, diffSize: null, diffDownUrl: null, diffSha2: null, sameS: null, size: null, releaseDate: null, icon: null, versionCode: null, versionName: null, oldVersionCode: null, oldVersionName: null, downUrl: null, newFeatures: null, releaseDateDesc: null, detailId: null, fullDownUrl: null, bundleSize: null, devType: null, isCompulsoryUpdate: null, isAutoUpdate: null, notRcmReason: null}

how I can correct this or any thing is missing ?

**Comment by darkang3lz92** [comment]
@MamdRoyalWorld @humzashahid-mobile 
Hi, I personally unable to reproduce the CHECK_FAILED issue. However I have added a new update with PR #8 to get more details  about the error in `v1.2.0`, you may try update to v1.2.0 and access the error detail through `PlatformException.details`. Refer [Huawei Error Result Code](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/appupdateclient-0000001050123641#section15712187193218) for more details regarding the error.

**Comment by darkang3lz92** [comment]
Closed due to no further response.

**Comment by EmelyanovSI** [comment]
> [@MamdRoyalWorld](https://github.com/MamdRoyalWorld) [@humzashahid-mobile](https://github.com/humzashahid-mobile) Hi, I personally unable to reproduce the CHECK_FAILED issue. However I have added a new update with PR [#8](https://github.com/darkang3lz92/huawei_in_app_update/pull/8) to get more details about the error in `v1.2.0`, you may try update to v1.2.0 and access the error detail through `PlatformException.details`. Refer [Huawei Error Result Code](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/appupdateclient-0000001050123641#section15712187193218) for more details regarding the error.


PlatformException(CHECK_FAILED, Update information fails to be queried, {code: 7, reason: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0}, null)

> 6: constant value CHECK_FAILED, indicating that the update information fails to be queried.
